### PR TITLE
Addresses handling of exponential numbers

### PR DESCRIPTION
**Pull request by mridgway**
The following description uses terminology pulled from the Number API for `toExponential` and `toFixed` to classify different string formats for numbers.

This PR makes the following assumptions about the library based on the existing tests:
 * Exponential numbers should not have been parsed previously (test for `"1e6"` returned `"1e6"`)
 * There was a bug that some exponentials were parsed (added a test for `"2e2"` which was parsed to `200`)
 * Strings that contained extraneous characters should not be parsed as floats (test for `"1.2.3"` returned `"1.2.3"` and not `1.2`)

Using these assumptions, I preserved backwards compatibility with all of the existing options and added a new non-default option to parse exponentials:

```js
lameJson.parse('2e2', { exponential: true }) // 200
```

The regular expressions used are loose for efficiency reasons and the parseFloat will return `NaN` on invalid numbers such as `"."` as shown in the test.

I also updated the tests to use `strictEqual` for type equality and added a few more cases.

### CODE REVIEW

**Comment by mridgway** [comment]
I was worried about overhead with running regular expressions on all values, but my tests showed that parsing two cases `2e2e` and `var test = '2e2' + Array(100000).fill('e').join('');` (a long string) were both about 20% faster with regex checks before `parseFloat` when running through the default settings.

**Comment by DonutEspresso** [comment]
Thanks, this looks great! My regex fu isn't up to par so I had @misterdjules and @daviande help take a look. They pointed out a few things that I think might be worth addressing:

* the EXPONENTIAL_REGEX would match something like `53.3.5e3`, which seems unintentional
* can we add a few tests to support negative numbers and floats?
* nit: I missed this on the last go around, but `isNaN()` appears to be a subset of `isFinite()` so we could probably do away with `isNaN()` 

Appreciate the help! 🎉

**Comment by mridgway** [comment]
Good catch on the regex and negatives. I'll also do away with `isNan`.

**Comment by DonutEspresso** [comment]
Thanks, this looks good to me now! 

I also learned today that lodash's `_.toFinite()` and `_.toNumber()` appear to handle all of these use cases through some clever use of `+` casting. On the surface this seems to address all the use cases we had in mind when `exponential: true`. Is it worth running through a quick test to see if that simplifies the logic dramatically? 

Then for properties, we could just set `exponential: false` which would opt out of the lodash functionality (falling back onto to parseFloat).

**Comment by mridgway** [comment]
Sure, I can take a look at Lodash for this.

The default currently is `exponential: false` so there wouldn't need to be any changes to properties except to upgrade the dependency.

**Comment by mridgway** [comment]
I updated the code to use lodash's `toNumber` which handles any invalid cases by returning `NaN`. This allowed me to get rid of the fixed float regex and just use the exponential one to filter out exponents.

**Comment by DonutEspresso** [comment]
Awesome, this looks good. Appreciate the help! I'll publish this as a minor given the new option, and it should just flow through for properties and other consumers. Does that work?

**Comment by mridgway** [comment]
@DonutEspresso That works for us. Thanks.

**Comment by DonutEspresso** [comment]
Published 1.5.0

**Pull request merged**
